[project]
name = "starbucks-mugs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "folium>=0.20.0",
    "geocoder>=1.38.1",
    "requests>=2.32.5",
]
